title: "TecDev"
description: "Technical insights for modern developers • Coding • DevOps • English for Tech"
url: "https://devgs8.github.io"
baseurl: ""

author:
  name: "DevGS8"
  github: "devgs8"
  twitter: # opcional

social:
  name: DevGS8
  links:
    - https://github.com/devgs8

github_username: devgs8

# SEO
logo: /assets/images/logo.png

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
