title: "TecDev"
description: "Technical insights for modern developers • Coding • DevOps • English for Tech"
url: "https://devgs8.github.io"
baseurl: ""

author:
  name: "DevGS8"
  github: "devgs8"

github_username: devgs8

# Favicon
favicon: /assets/images/favicon.ico

# Navigation menu
header_pages:
  - index.md
  - about.md

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
